# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  SBT_THREAD_NUMBER: 2 

trigger:
- master

pool:
  name: Hosted Ubuntu 1604
  timeoutInMinutes: 360

steps:
- script: |
   echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
   sudo apt-key adv --keyserver hkps://keyserver.ubuntu.com:443 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823
   sudo apt-get update --allow-unauthenticated
   sudo apt-get install sbt --allow-unauthenticated
  displayName: 'Command Line Script'

- script: |
   sbt -J-Xms5G -J-Xmx5G -J-XX:+UseConcMarkSweepGC -J-XX:+CMSClassUnloadingEnabled  dex-it/docker
   docker images
  displayName: 'Build docker and show'

- script: 'sbt -J-Xms5G -J-Xmx5G -J-XX:+UseConcMarkSweepGC -J-XX:+CMSClassUnloadingEnabled  test'
  displayName: 'Run tests '

- task: PublishTestResults@2
  displayName: 'Publish Test Results target/test-reports/*.xml copy'
  inputs:
    testResultsFiles: 'target/test-reports/*.xml'
  condition: succeededOrFailed()
